const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";

const SELECT_ALBUM = "SELECT_ALBUM";

const FETCH_PHOTOS_START = "FETCH_PHOTOS_START";
const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
const FETCH_PHOTOS_ERROR = "FETCH_PHOTOS_ERROR";

export {
    ADD_TO_FAVOURITES,
    REMOVE_FROM_FAVOURITES,
    SELECT_ALBUM,
    FETCH_PHOTOS_START,
    FETCH_PHOTOS_ERROR,
    FETCH_PHOTOS_SUCCESS
};
